---
abstract: 'Distributed Project Management Database'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
  FindBin: 0
  Test::Database: 1.11
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-curo
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  AnyEvent::Handle: 0
  Carp: 0
  Cwd: 0
  Data::UUID: 0
  EV: 0
  File::HomeDir: 0
  File::Spec::Functions: 0
  Getopt::Long::Descriptive: 0
  JSON::XS: 0
  Log::Any: 0
  Moo: 0
  SQL::DB: 0.19_11
  SQL::DBx::Deploy: 0
  SQL::DBx::Sequence: 0
  SQL::DBx::Simple: 0
  Sub::Exporter: 0
  Sys::Cmd: 0.07_2
  Term::ANSIColor: 0
  Term::Prompt: 0
  Time::Duration: 0
  Time::Local: 0
  Try::Tiny: 0
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/gpl-3.0.html
  repository: git://github.com/mlawren/curo.git
version: 0.01_02
