---
abstract: 'Distributed Project Management System'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  FindBin: 0
  IO::Capture::Stdout: 0
  Test::Database: 1.11
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-curo
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent: 0
  AnyEvent::Handle: 0
  Carp: 0
  Cwd: 0
  DBD::SQLite: 1.37
  Digest::SHA1: 0
  Exporter::Tidy: 0
  File::Basename: 0
  File::HomeDir: 0
  File::Temp: 0
  File::chdir: 0
  IO::Pager: 0.24
  JSON::XS: 0
  Log::Any: 0
  Log::Dispatch: 0
  Moo: 0
  OptArgs: 0
  Path::Class: 0
  Proc::InvokeEditor: 0
  SQL::DB: 0.191.0
  SQL::DBx::Deploy: 0
  SQL::DBx::SQLite: 0
  Sys::Cmd: 0.08
  Term::ANSIColor: 0
  Term::Prompt: 0
  Term::Size: 0
  Text::Autoformat: 0
  Text::FormatTable: 0
  Time::Duration: 0
  Time::Piece: 0
  Try::Tiny: 0
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/gpl-3.0.html
  repository: https://github.com/mlawren/curo
version: 0.0.2_01
