#!/usr/bin/env perl
# A test 'curo' that uses the local ../lib dir.
use strict;
use warnings;
use OptArgs qw/dispatch/;
use FindBin;
use lib "$FindBin::Bin/../lib";

dispatch(qw/run App::curo::Cmd/);

