#!/usr/bin/env perl
# A test 'curo-sync' that uses the local ../lib dir.
use strict;
use warnings;
use OptArgs qw/dispatch/;
use FindBin;
use lib "$FindBin::Bin/../lib";

dispatch(qw/run App::curo_sync/);

